[package]
name = "web-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
axum = { version = "0.8", default-features = false, features = ["tokio", "http1"] }
tokio = { workspace = true }
leptos = { version = "0.8", features = ["ssr"] }
leptos_axum = "0.8"
leptos_config = "0.8"
web-ui = { path = "../web-ui" }
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs", "set-header"] }
flate2 = "1"
brotli = "8"

[features]
default = ["ssr"]
ssr = ["web-ui/ssr"]
