use app::AppState;
use axum::{Router, routing::get};

use crate::handlers;

pub(crate) fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/notebooks",
            get(handlers::list_notebooks).post(handlers::create_notebook),
        )
        .route(
            "/notebooks/{id}",
            get(handlers::get_notebook)
                .patch(handlers::update_notebook)
                .put(handlers::update_notebook)
                .delete(handlers::delete_notebook),
        )
        .route(
            "/notebooks/{id}/documents",
            axum::routing::post(handlers::create_document_upload_handler),
        )
        .route(
            "/notebooks/{id}/sources/url",
            axum::routing::post(handlers::add_url_source_handler),
        )
        .route(
            "/notebooks/{id}/analysis",
            get(handlers::get_notebook_analysis_handler),
        )
        .route(
            "/notebooks/{id}/notes",
            get(handlers::list_notebook_notes_handler)
                .post(handlers::create_notebook_note_handler),
        )
        .route(
            "/notebooks/{id}/notes/{note_id}",
            get(handlers::get_notebook_note_handler)
                .put(handlers::update_notebook_note_handler)
                .delete(handlers::delete_notebook_note_handler),
        )
        .route(
            "/notebooks/{id}/notes/{note_id}/promote-to-source",
            axum::routing::post(handlers::promote_notebook_note_handler),
        )
        .route(
            "/notebooks/{id}/share",
            axum::routing::post(handlers::create_share_handler),
        )
        .route(
            "/notebooks/{id}/share/settings",
            get(handlers::get_share_settings_handler)
                .put(handlers::update_share_settings_handler),
        )
        .route(
            "/notebooks/{id}/share/analytics",
            get(handlers::get_share_analytics_handler),
        )
        .route(
            "/notebooks/{id}/share/access-logs",
            get(handlers::get_share_access_logs_handler),
        )
        .route(
            "/notebooks/{id}/share/{token}",
            axum::routing::delete(handlers::revoke_share_handler),
        )
        .route(
            "/notebooks/{id}/access-level",
            axum::routing::post(handlers::update_access_level_handler),
        )
        .route("/documents", get(handlers::list_documents_handler))
        .route(
            "/documents/{document_id}",
            axum::routing::put(handlers::update_document_handler)
                .delete(handlers::delete_document_handler),
        )
        .route(
            "/documents/{document_id}/status",
            get(handlers::get_document_status_handler),
        )
        .route(
            "/documents/{document_id}/content",
            get(handlers::get_document_content_handler),
        )
        .route(
            "/documents/{document_id}/parsed-preview",
            get(handlers::get_parsed_preview_handler),
        )
        .route(
            "/documents/{document_id}/reindex",
            axum::routing::post(handlers::reindex_document_handler),
        )
        .route(
            "/documents/{document_id}/complete-upload",
            axum::routing::post(handlers::complete_document_upload_handler),
        )
        .route("/sources", get(handlers::list_sources_handler))
        .route(
            "/notebooks/{id}/api-keys",
            get(handlers::list_api_keys_handler).post(handlers::create_api_key_handler),
        )
        .route(
            "/notebooks/{id}/api-keys/{key_id}",
            axum::routing::delete(handlers::revoke_api_key_handler),
        )
        .route(
            "/notebooks/{id}/members",
            get(handlers::list_members_handler),
        )
        .route(
            "/notebooks/{id}/members/invite",
            axum::routing::post(handlers::invite_member_handler),
        )
        .route(
            "/notebooks/{id}/members/{member_id}/accept",
            axum::routing::post(handlers::accept_member_handler),
        )
        .route(
            "/notebooks/{id}/members/{member_id}/decline",
            axum::routing::post(handlers::decline_member_handler),
        )
        .route(
            "/notebooks/{id}/members/{member_id}",
            axum::routing::delete(handlers::remove_member_handler),
        )
        .route("/notifications", get(handlers::list_notifications_handler))
        .route(
            "/notifications/{notification_id}/read",
            axum::routing::post(handlers::mark_notification_read_handler),
        )
}
