use app_bootstrap::AppState;
use axum::{Router, routing::get};

use crate::handlers;

/// Workspace product routes (notebook path removed — product not launched).
pub(crate) fn router() -> Router<AppState> {
    Router::new()
        .merge(workspace_scoped_router("/workspaces"))
        .route("/documents", get(handlers::list_documents_handler))
        .route(
            "/documents/{document_id}",
            axum::routing::put(handlers::update_document_handler)
                .delete(handlers::delete_document_handler),
        )
        .route(
            "/documents/{document_id}/status",
            get(handlers::get_document_status_handler),
        )
        .route(
            "/documents/{document_id}/content",
            get(handlers::get_document_content_handler),
        )
        .route(
            "/documents/{document_id}/parsed-preview",
            get(handlers::get_parsed_preview_handler),
        )
        .route(
            "/documents/{document_id}/reindex",
            axum::routing::post(handlers::reindex_document_handler),
        )
        .route(
            "/documents/{document_id}/complete-upload",
            axum::routing::post(handlers::complete_document_upload_handler),
        )
        .route("/sources", get(handlers::list_sources_handler))
        .route(
            "/org/api-keys",
            get(handlers::list_org_api_keys_handler).post(handlers::create_org_api_key_handler),
        )
        .route(
            "/org/api-keys/{key_id}",
            axum::routing::delete(handlers::revoke_org_api_key_handler),
        )
        .route("/notifications", get(handlers::list_notifications_handler))
        .route(
            "/notifications/{notification_id}/read",
            axum::routing::post(handlers::mark_notification_read_handler),
        )
}

fn workspace_scoped_router(prefix: &str) -> Router<AppState> {
    Router::new()
        .route(
            prefix,
            get(handlers::list_notebooks).post(handlers::create_notebook),
        )
        .route(
            &format!("{prefix}/{{id}}"),
            get(handlers::get_notebook)
                .patch(handlers::update_notebook)
                .put(handlers::update_notebook)
                .delete(handlers::delete_notebook),
        )
        .route(
            &format!("{prefix}/{{id}}/documents"),
            axum::routing::post(handlers::create_document_upload_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/sources/url"),
            axum::routing::post(handlers::add_url_source_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/analysis"),
            get(handlers::get_notebook_analysis_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/notes"),
            get(handlers::list_notebook_notes_handler).post(handlers::create_notebook_note_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/notes/{{note_id}}"),
            get(handlers::get_notebook_note_handler)
                .put(handlers::update_notebook_note_handler)
                .delete(handlers::delete_notebook_note_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/notes/{{note_id}}/promote-to-source"),
            axum::routing::post(handlers::promote_notebook_note_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/share"),
            axum::routing::post(handlers::create_share_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/share/settings"),
            get(handlers::get_share_settings_handler).put(handlers::update_share_settings_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/share/analytics"),
            get(handlers::get_share_analytics_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/share/access-logs"),
            get(handlers::get_share_access_logs_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/share/{{token}}"),
            axum::routing::delete(handlers::revoke_share_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/access-level"),
            axum::routing::post(handlers::update_access_level_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/api-keys"),
            get(handlers::list_api_keys_handler).post(handlers::create_api_key_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/api-keys/{{key_id}}"),
            axum::routing::delete(handlers::revoke_api_key_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/members"),
            get(handlers::list_members_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/members/invite"),
            axum::routing::post(handlers::invite_member_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/members/{{member_id}}/accept"),
            axum::routing::post(handlers::accept_member_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/members/{{member_id}}/decline"),
            axum::routing::post(handlers::decline_member_handler),
        )
        .route(
            &format!("{prefix}/{{id}}/members/{{member_id}}"),
            axum::routing::delete(handlers::remove_member_handler),
        )
}
