/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: ["*.html", "./crates/**/*.rs"],
  },
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        "input-background": "hsl(var(--input-background))",
        "switch-background": "hsl(var(--switch-background))",
        ring: "hsl(var(--ring))",
        "chart-1": "hsl(var(--chart-1))",
        "chart-2": "hsl(var(--chart-2))",
        "chart-3": "hsl(var(--chart-3))",
        "chart-4": "hsl(var(--chart-4))",
        "chart-5": "hsl(var(--chart-5))",
        sidebar: "hsl(var(--sidebar))",
        "sidebar-foreground": "hsl(var(--sidebar-foreground))",
        "sidebar-primary": "hsl(var(--sidebar-primary))",
        "sidebar-primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        "sidebar-accent": "hsl(var(--sidebar-accent))",
        "sidebar-accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        "sidebar-border": "hsl(var(--sidebar-border))",
        "sidebar-ring": "hsl(var(--sidebar-ring))",
        "workspace-shell": "hsl(var(--workspace-shell))",
        "workspace-foreground": "hsl(var(--workspace-foreground))",
        "workspace-panel": "hsl(var(--workspace-panel))",
        "workspace-panel-muted": "hsl(var(--workspace-panel-muted))",
        "workspace-rail": "hsl(var(--workspace-rail))",
        "workspace-rail-strong": "hsl(var(--workspace-rail-strong))",
        "workspace-border": "hsl(var(--workspace-border))",
        "workspace-primary": "hsl(var(--workspace-primary))",
        "workspace-primary-foreground": "hsl(var(--workspace-primary-foreground))",
        "workspace-secondary": "hsl(var(--workspace-secondary))",
        "workspace-secondary-foreground": "hsl(var(--workspace-secondary-foreground))",
        "workspace-muted": "hsl(var(--workspace-muted))",
        "workspace-muted-foreground": "hsl(var(--workspace-muted-foreground))",
        "workspace-accent": "hsl(var(--workspace-accent))",
        "workspace-accent-foreground": "hsl(var(--workspace-accent-foreground))",
        "workspace-surface": "hsl(var(--workspace-surface))",
        "workspace-surface-muted": "hsl(var(--workspace-surface-muted))",
        "workspace-pill": "hsl(var(--workspace-pill))",
        "workspace-input": "hsl(var(--workspace-input))",
        "workspace-input-border": "hsl(var(--workspace-input-border))",
        "workspace-menu": "hsl(var(--workspace-menu))",
        "workspace-menu-hover": "hsl(var(--workspace-menu-hover))",
        "workspace-shadow": "hsl(var(--workspace-shadow))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "Inter Variable",
          "Inter",
          "SF Pro Text",
          "PingFang SC",
          "Noto Sans CJK SC",
          "Microsoft YaHei UI",
          "system-ui",
          "sans-serif",
        ],
      },
      boxShadow: {
        'popover': '0 10px 40px -10px rgba(0,0,0,0.15), 0 4px 6px -4px rgba(0,0,0,0.05)',
        'workspace': '0 18px 48px -18px rgba(15, 30, 60, 0.24)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slideDown 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scaleIn 0.18s cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse-subtle': 'pulseSubtle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.98)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.85' },
        }
      }
    },
  },
  plugins: [],
}
