[package]
name = "web-sdk"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
contracts = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures-util = { workspace = true }
tokio-util = { workspace = true }
async-stream = "0.3"
futures-channel = "0.3"
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = [
    "AbortController",
    "AbortSignal",
    "Headers",
    "ReadableStream",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Storage",
    "Document",
    "HtmlDocument",
    "Location",
    "Window",
    "Blob",
] }
wasm-streams = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
