use std::collections::HashMap;
use std::sync::OnceLock;

use super::Skill;

static STANDARD_REGISTRY: OnceLock<PromptRegistry> = OnceLock::new();

/// Central registry for all prompt assets (Skills).
///
/// CDS v1.1 / ADR-0007: loads prompt disclosure assets from build.rs.
///
/// Future work may load these from external storage for hot-swapping.
pub struct PromptRegistry {
    skills: HashMap<String, Skill>,
}

impl PromptRegistry {
    /// Build the standard registry by including the code generated by build.rs.
    ///
    /// build.rs scans CDS A/B roots at compile time and emits a registration
    /// block for every `SKILL.md` found, including any `assets/` and `reference/`
    /// files alongside it. This follows the Perplexity best practice of
    /// directory-scan discovery rather than hard-coded registration.
    pub fn standard() -> Self {
        let mut skills = HashMap::new();
        include!(concat!(env!("OUT_DIR"), "/generated_registry.rs"));
        let registry = Self { skills };
        registry.validate_dependencies();
        registry
    }

    /// Validate that the skill dependency graph has no cycles and all
    /// referenced dependencies exist.
    fn validate_dependencies(&self) {
        // 1. Check all dependencies exist.
        for skill in self.iter_skills() {
            for dep in skill.dependencies() {
                assert!(
                    self.skill(dep).is_some(),
                    "Skill '{}' depends on missing skill '{}'",
                    skill.id(),
                    dep
                );
            }
        }

        // 2. Detect cycles via DFS coloring (0=white, 1=gray, 2=black).
        let mut color: std::collections::HashMap<String, u8> =
            self.skills.keys().map(|k| (k.clone(), 0)).collect();
        let mut stack = Vec::new();

        for id in self.skills.keys() {
            if color[id] == 0 {
                Self::dfs_cycle_check(id, &self.skills, &mut color, &mut stack);
            }
        }
    }

    fn dfs_cycle_check(
        id: &str,
        skills: &std::collections::HashMap<String, Skill>,
        color: &mut std::collections::HashMap<String, u8>,
        stack: &mut Vec<String>,
    ) {
        color.insert(id.to_string(), 1); // gray
        stack.push(id.to_string());

        if let Some(skill) = skills.get(id) {
            for dep in skill.dependencies() {
                match color.get(dep).copied().unwrap_or(0) {
                    0 => Self::dfs_cycle_check(dep, skills, color, stack),
                    1 => {
                        let cycle: Vec<String> =
                            stack.iter().skip_while(|s| *s != dep).cloned().collect();
                        panic!(
                            "Skill dependency cycle detected: {} -> {}",
                            cycle.join(" -> "),
                            dep
                        );
                    }
                    _ => {} // black, already fully explored
                }
            }
        }

        stack.pop();
        color.insert(id.to_string(), 2); // black
    }

    /// Look up a skill by its canonical id.
    pub fn skill(&self, id: &str) -> Option<&Skill> {
        self.skills.get(id)
    }

    /// Iterate over all registered skills.
    pub fn iter_skills(&self) -> impl Iterator<Item = &Skill> {
        self.skills.values()
    }

    /// Return a lazily-initialised global singleton of the standard registry.
    ///
    /// Prefer this over [`Self::standard()`] in hot paths (e.g. inside the ReAct
    /// loop) to avoid reconstructing the HashMap on every iteration.
    pub fn standard_cached() -> &'static Self {
        STANDARD_REGISTRY.get_or_init(Self::standard)
    }

    #[cfg(test)]
    fn from_skills(skills: HashMap<String, Skill>) -> Self {
        let registry = Self { skills };
        registry.validate_dependencies();
        registry
    }

    #[cfg(test)]
    fn from_skills_unchecked(skills: HashMap<String, Skill>) -> Self {
        Self { skills }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prompt_registry_standard_cached_is_lazy() {
        let r1 = PromptRegistry::standard_cached();
        let r2 = PromptRegistry::standard_cached();
        assert!(
            std::ptr::eq(r1, r2),
            "standard_cached should return the same instance"
        );
    }

    #[test]
    fn prompt_registry_standard_cached_loads_cds_assets() {
        let registry = PromptRegistry::standard_cached();
        assert!(registry.skill("codegen").is_some());
        assert!(registry.skill("writing").is_some());
        assert!(registry.skill("format").is_some());
        assert!(registry.skill("memory").is_some());
        assert!(registry.skill("search").is_some());
        assert!(registry.skill("rag-answer").is_some());
        assert!(registry.skill("search-answer").is_some());
        assert!(registry.skill("chat").is_some());
        assert!(registry.skill("rag-system").is_some());
        assert!(registry.skill("dense-retrieval").is_none());
        assert!(registry.skill("doc-index").is_none());
        assert!(registry.skill("triplet-extraction").is_none());
        assert!(registry.skill("session-summary").is_none());
    }

    #[test]
    fn all_skills_have_non_empty_description() {
        let registry = PromptRegistry::standard_cached();
        for skill in registry.iter_skills() {
            assert!(
                !skill.description().is_empty(),
                "Skill '{}' has empty description",
                skill.id()
            );
        }
    }

    #[test]
    fn atomic_retrieval_tools_are_not_prompt_skills() {
        let registry = PromptRegistry::standard_cached();
        for name in &[
            "dense-retrieval",
            "lexical-retrieval",
            "graph-retrieval",
            "doc-summary",
            "doc-index",
            "doc-metadata",
            "index-lookup",
        ] {
            assert!(
                registry.skill(name).is_none(),
                "tool spec '{name}' should not be registered as a prompt skill"
            );
        }
    }

    #[test]
    fn dependency_validation_detects_missing_dependency() {
        let mut skills = std::collections::HashMap::new();
        skills.insert(
            "a".to_string(),
            Skill::with_meta(
                "a",
                "desc",
                "body",
                "1.0",
                vec!["missing".to_string()],
                std::collections::HashMap::new(),
            ),
        );
        let registry = PromptRegistry::from_skills_unchecked(skills);
        let result = std::panic::catch_unwind(|| registry.validate_dependencies());
        assert!(result.is_err(), "should panic on missing dependency");
    }

    #[test]
    fn dependency_validation_detects_cycle() {
        let mut skills = std::collections::HashMap::new();
        skills.insert(
            "a".to_string(),
            Skill::with_meta(
                "a",
                "desc",
                "body",
                "1.0",
                vec!["b".to_string()],
                std::collections::HashMap::new(),
            ),
        );
        skills.insert(
            "b".to_string(),
            Skill::with_meta(
                "b",
                "desc",
                "body",
                "1.0",
                vec!["a".to_string()],
                std::collections::HashMap::new(),
            ),
        );
        let registry = PromptRegistry::from_skills_unchecked(skills);
        let result = std::panic::catch_unwind(|| registry.validate_dependencies());
        assert!(result.is_err(), "should panic on cyclic dependency");
    }

    #[test]
    fn dependency_validation_passes_for_acyclic_graph() {
        let mut skills = std::collections::HashMap::new();
        skills.insert(
            "base".to_string(),
            Skill::with_meta(
                "base",
                "desc",
                "body",
                "1.0",
                vec![],
                std::collections::HashMap::new(),
            ),
        );
        skills.insert(
            "derived".to_string(),
            Skill::with_meta(
                "derived",
                "desc",
                "body",
                "1.0",
                vec!["base".to_string()],
                std::collections::HashMap::new(),
            ),
        );
        let registry = PromptRegistry::from_skills(skills);
        // Should not panic (validate_dependencies called inside from_skills)
        drop(registry);
    }
}
