use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

/// Build script that scans `prompts/skills/` and generates the skill registry.
///
/// Perplexity best practice: skills are discovered by directory scan rather than
/// hard-coded registration, so adding a new skill directory automatically
/// includes it in the binary.
///
/// All file contents (SKILL.md, assets/, references/) are embedded as string
/// literals in the generated code, avoiding `include_str!` path-resolution
/// issues when OUT_DIR lives outside the workspace.
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    // Path from crates/app/build.rs to workspace root prompts/skills/
    let skills_dir = Path::new(&manifest_dir).join("../../prompts/skills");
    let skills_dir = skills_dir.canonicalize().expect("prompts/skills/ must exist");

    let mut generated = String::new();
    generated.push_str("// AUTOGENERATED BY build.rs — do not edit manually.\n");
    generated.push_str("// Scans prompts/skills/ at compile time and generates registration calls.\n\n");

    let mut skill_entries = Vec::new();

    for entry in fs::read_dir(&skills_dir).expect("read skills dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }

        let skill_name = path.file_name().unwrap().to_string_lossy().to_string();
        let skill_md_path = path.join("SKILL.md");
        if !skill_md_path.exists() {
            continue;
        }

        // Validate frontmatter at build time (fail fast on malformed skills)
        let content = fs::read_to_string(&skill_md_path).expect("read SKILL.md");
        let (fm, _) = parse_frontmatter(&content);
        if let Some(ref f) = fm {
            assert!(
                !f.name.is_empty(),
                "Skill '{}' frontmatter missing 'name'",
                skill_name
            );
            assert!(
                !f.description.is_empty(),
                "Skill '{}' frontmatter missing 'description'",
                skill_name
            );
        }

        // Scan assets/
        let assets_dir = path.join("assets");
        let asset_files = if assets_dir.exists() {
            collect_text_files(&assets_dir)
        } else {
            Vec::new()
        };

        // Scan references/
        let refs_dir = path.join("references");
        let ref_files = if refs_dir.exists() {
            collect_text_files(&refs_dir)
        } else {
            Vec::new()
        };

        skill_entries.push((skill_name, content, asset_files, ref_files));
    }

    // Sort for deterministic output
    skill_entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate registration code
    generated.push_str("{\n");
    generated.push_str("    let mut register = |id: &str, content: &str, assets: std::collections::HashMap<String, String>, references: std::collections::HashMap<String, String>| {\n");
    generated.push_str("        let (frontmatter, body) = super::skill_frontmatter::parse_skill_file(content);\n");
    generated.push_str("        let skill = match frontmatter {\n");
    generated.push_str("            Some(fm) => super::Skill::with_meta(\n");
    generated.push_str("                &fm.name,\n");
    generated.push_str("                &fm.description,\n");
    generated.push_str("                body,\n");
    generated.push_str("                &fm.version,\n");
    generated.push_str("                fm.depends,\n");
    generated.push_str("                fm.metadata,\n");
    generated.push_str("            )\n");
    generated.push_str("            .with_assets(assets)\n");
    generated.push_str("            .with_references(references),\n");
    generated.push_str("            None => super::Skill::new(id, \"\", body)\n");
    generated.push_str("            .with_assets(assets)\n");
    generated.push_str("            .with_references(references),\n");
    generated.push_str("        };\n");
    generated.push_str("        skills.insert(id.to_string(), skill);\n");
    generated.push_str("    };\n\n");

    for (skill_name, content, assets, refs) in &skill_entries {
        let content_literal = raw_string_literal(content);

        // Generate assets HashMap
        let assets_code = if assets.is_empty() {
            "std::collections::HashMap::new()".to_string()
        } else {
            let mut code = String::from("{\n            let mut m = std::collections::HashMap::new();\n");
            for (file_name, file_content) in assets {
                let lit = raw_string_literal(file_content);
                code.push_str(&format!(
                    "            m.insert(\"{}\".to_string(), {}.to_string());\n",
                    escape_string(file_name), lit
                ));
            }
            code.push_str("            m\n        }");
            code
        };

        // Generate references HashMap
        let refs_code = if refs.is_empty() {
            "std::collections::HashMap::new()".to_string()
        } else {
            let mut code = String::from("{\n            let mut m = std::collections::HashMap::new();\n");
            for (file_name, file_content) in refs {
                let lit = raw_string_literal(file_content);
                code.push_str(&format!(
                    "            m.insert(\"{}\".to_string(), {}.to_string());\n",
                    escape_string(file_name), lit
                ));
            }
            code.push_str("            m\n        }");
            code
        };

        generated.push_str(&format!(
            "    register(\"{}\", {}, {}, {});\n",
            skill_name, content_literal, assets_code, refs_code
        ));
    }

    generated.push_str("}\n");

    let out_path = Path::new(&out_dir).join("generated_registry.rs");
    let mut file = fs::File::create(&out_path).expect("create generated_registry.rs");
    file.write_all(generated.as_bytes())
        .expect("write generated_registry.rs");

    // Rerun if skills directory changes
    println!("cargo:rerun-if-changed={}", skills_dir.display());
}

/// Produce a raw string literal `r###"..."###` with enough `#` delimiters
/// so the content cannot accidentally close the literal.
fn raw_string_literal(content: &str) -> String {
    let mut hashes = 1;
    loop {
        let delimiter = "#".repeat(hashes);
        let open = format!("r{}\"", delimiter);
        let close = format!("\"{}", delimiter);
        if !content.contains(&close) {
            return format!("{}{}{}", open, content, close);
        }
        hashes += 1;
        if hashes > 20 {
            panic!("Cannot find suitable raw string delimiter");
        }
    }
}

/// Escape a string for use inside a regular `\"...\"` Rust string literal.
fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('\"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[derive(Debug)]
struct Frontmatter {
    name: String,
    description: String,
    version: String,
    depends: Vec<String>,
    /// Extra metadata fields parsed from frontmatter (applicable_strategies, risk_level, etc.)
    metadata: std::collections::HashMap<String, String>,
}

fn parse_frontmatter(content: &str) -> (Option<Frontmatter>, String) {
    let trimmed = content.trim_start();
    if !trimmed.starts_with("---") {
        return (None, content.to_string());
    }
    let after_open = &trimmed[3..];
    let after_open = after_open.strip_prefix('\r').unwrap_or(after_open);
    let after_open = after_open.strip_prefix('\n').unwrap_or(after_open);
    let Some(close_idx) = after_open.find("\n---") else {
        return (None, content.to_string());
    };
    let yaml_block = &after_open[..close_idx];
    let fm = parse_yaml_block(yaml_block);
    (Some(fm), String::new())
}

fn parse_yaml_block(block: &str) -> Frontmatter {
    let mut fm = Frontmatter {
        name: String::new(),
        description: String::new(),
        version: "1.0".to_string(),
        depends: Vec::new(),
        metadata: std::collections::HashMap::new(),
    };
    for line in block.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, raw_value)) = line.split_once(':') else { continue };
        let key = key.trim();
        let raw_value = raw_value.trim();
        match key {
            "name" => fm.name = strip_quotes(raw_value).to_string(),
            "description" => fm.description = strip_quotes(raw_value).to_string(),
            "version" => fm.version = strip_quotes(raw_value).to_string(),
            "depends" => fm.depends = parse_string_array(raw_value),
            other => {
                fm.metadata.insert(other.to_string(), strip_quotes(raw_value).to_string());
            }
        }
    }
    fm
}

fn strip_quotes(s: &str) -> &str {
    let s = s.trim();
    if s.len() >= 2 {
        let first = s.chars().next().unwrap();
        let last = s.chars().last().unwrap();
        if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
            return &s[1..s.len() - 1];
        }
    }
    s
}

fn parse_string_array(s: &str) -> Vec<String> {
    let s = s.trim();
    if !s.starts_with('[') || !s.ends_with(']') {
        return Vec::new();
    }
    let inner = &s[1..s.len() - 1];
    if inner.trim().is_empty() {
        return Vec::new();
    }
    inner
        .split(',')
        .map(|item| strip_quotes(item.trim()).to_string())
        .filter(|item| !item.is_empty())
        .collect()
}

fn collect_text_files(dir: &Path) -> Vec<(String, String)> {
    let mut files = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file()
                && let Some(name) = path.file_name().and_then(|n| n.to_str())
                    && let Ok(content) = fs::read_to_string(&path) {
                        files.push((name.to_string(), content));
                    }
        }
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}
