use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

    /// ADR-0007: scan prompt disclosure assets at compile time.
    /// Scanned: prompts/clusters/, prompts/synthesis/, prompts/orchestrators/.
    /// Excluded by design: prompts/deprecated/atomic-tools/ (legacy docs; tools via mode config + SkillComponent).
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let prompts_root = Path::new(&manifest_dir).join("../../prompts");
    let prompts_root = prompts_root.canonicalize().expect("prompts/ must exist");

    let mut skill_entries = Vec::new();

    let scan_roots = [prompts_root.join("clusters")];
    for root in &scan_roots {
        if root.exists() {
            scan_skill_directories(root, &mut skill_entries);
        }
    }

    for flat_root in ["synthesis", "orchestrators"] {
        let dir = prompts_root.join(flat_root);
        if dir.exists() {
            scan_flat_markdown(&dir, &mut skill_entries);
        }
    }

    skill_entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::new();
    generated.push_str("// AUTOGENERATED BY build.rs — do not edit manually.\n");
    generated.push_str("// ADR-0007: clusters + synthesis + orchestrators\n\n");
    generated.push_str("{\n");
    generated.push_str("    let mut register = |id: &str, content: &str, assets: std::collections::HashMap<String, String>, references: std::collections::HashMap<String, String>, input_schema: Option<&str>, output_schema: Option<&str>| {\n");
    generated.push_str(
        "        let (frontmatter, body) = super::skill_frontmatter::parse_skill_file(content);\n",
    );
    generated.push_str("        let mut skill = match frontmatter {\n");
    generated.push_str("            Some(fm) => super::Skill::with_meta(\n");
    generated.push_str("                &fm.name,\n");
    generated.push_str("                &fm.description,\n");
    generated.push_str("                body,\n");
    generated.push_str("                &fm.version,\n");
    generated.push_str("                fm.depends,\n");
    generated.push_str("                fm.metadata,\n");
    generated.push_str("            ),\n");
    generated.push_str("            None => super::Skill::new(id, \"\", body),\n");
    generated.push_str("        };\n");
    generated.push_str("        skill = skill.with_assets(assets).with_references(references);\n");
    generated.push_str("        if let Some(schema) = input_schema {\n");
    generated.push_str("            skill = skill.with_input_schema(schema);\n");
    generated.push_str("        }\n");
    generated.push_str("        if let Some(schema) = output_schema {\n");
    generated.push_str("            skill = skill.with_output_schema(schema);\n");
    generated.push_str("        }\n");
    generated.push_str("        skills.insert(id.to_string(), skill);\n");
    generated.push_str("    };\n\n");

    for (skill_name, content, assets, refs, input_schema, output_schema) in &skill_entries {
        let content_literal = raw_string_literal(content);
        let assets_code = hashmap_literal(assets);
        let refs_code = hashmap_literal(refs);
        let input_schema_literal = match input_schema {
            Some(s) => format!("Some({})", raw_string_literal(s)),
            None => "None".to_string(),
        };
        let output_schema_literal = match output_schema {
            Some(s) => format!("Some({})", raw_string_literal(s)),
            None => "None".to_string(),
        };
        generated.push_str(&format!(
            "    register(\"{}\", {}, {}, {}, {}, {});\n",
            skill_name,
            content_literal,
            assets_code,
            refs_code,
            input_schema_literal,
            output_schema_literal
        ));
    }
    generated.push_str("}\n");

    let out_path = Path::new(&out_dir).join("generated_registry.rs");
    fs::File::create(&out_path)
        .expect("create generated_registry.rs")
        .write_all(generated.as_bytes())
        .expect("write generated_registry.rs");

    println!("cargo:rerun-if-changed={}", prompts_root.display());
}

type SkillEntry = (
    String,
    String,
    Vec<(String, String)>,
    Vec<(String, String)>,
    Option<String>,
    Option<String>,
);

fn scan_skill_directories(root: &Path, out: &mut Vec<SkillEntry>) {
    for entry in fs::read_dir(root).expect("read prompt root") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let skill_md = path.join("SKILL.md");
        if !skill_md.exists() {
            continue;
        }
        let dir_name = path.file_name().unwrap().to_string_lossy().to_string();
        if let Some(entry) = load_skill_entry(&skill_md, &dir_name) {
            out.push(entry);
        }
    }
}

fn scan_flat_markdown(root: &Path, out: &mut Vec<SkillEntry>) {
    for entry in fs::read_dir(root).expect("read flat dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        if let Some(entry) = load_skill_entry(&path, &stem) {
            out.push(entry);
        }
    }
}

fn load_skill_entry(skill_path: &Path, fallback_id: &str) -> Option<SkillEntry> {
    let content = fs::read_to_string(skill_path).expect("read skill md");
    let (fm, _) = parse_frontmatter(&content);
    if let Some(ref f) = fm {
        assert!(
            !f.name.is_empty(),
            "Skill at {:?} frontmatter missing 'name'",
            skill_path
        );
    }
    let registry_id = fm
        .as_ref()
        .map(|f| f.name.clone())
        .filter(|n| !n.is_empty())
        .unwrap_or_else(|| fallback_id.to_string());

    let parent = skill_path.parent()?;
    let assets_dir = parent.join("assets");
    let ref_dir = parent.join("reference");
    let asset_files = if assets_dir.exists() {
        collect_text_files(&assets_dir)
    } else {
        Vec::new()
    };
    let ref_files = if ref_dir.exists() {
        collect_text_files(&ref_dir)
    } else {
        Vec::new()
    };
    let input_schema = ref_dir
        .join("args-schema.md")
        .exists()
        .then(|| {
            extract_json_code_block(&fs::read_to_string(ref_dir.join("args-schema.md")).unwrap())
        })
        .flatten();
    let output_schema = ref_dir
        .join("output-schema.md")
        .exists()
        .then(|| {
            extract_json_code_block(&fs::read_to_string(ref_dir.join("output-schema.md")).unwrap())
        })
        .flatten();

    Some((
        registry_id,
        content,
        asset_files,
        ref_files,
        input_schema,
        output_schema,
    ))
}

fn hashmap_literal(items: &[(String, String)]) -> String {
    if items.is_empty() {
        return "std::collections::HashMap::new()".to_string();
    }
    let mut code = String::from("{\n            let mut m = std::collections::HashMap::new();\n");
    for (file_name, file_content) in items {
        code.push_str(&format!(
            "            m.insert(\"{}\".to_string(), {}.to_string());\n",
            escape_string(file_name),
            raw_string_literal(file_content)
        ));
    }
    code.push_str("            m\n        }");
    code
}

fn raw_string_literal(content: &str) -> String {
    let mut hashes = 1;
    loop {
        let delimiter = "#".repeat(hashes);
        let open = format!("r{}\"", delimiter);
        let close = format!("\"{}", delimiter);
        if !content.contains(&close) {
            return format!("{}{}{}", open, content, close);
        }
        hashes += 1;
        if hashes > 20 {
            panic!("Cannot find suitable raw string delimiter");
        }
    }
}

fn escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('\"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[derive(Debug)]
struct Frontmatter {
    name: String,
    description: String,
    version: String,
    depends: Vec<String>,
    metadata: std::collections::HashMap<String, String>,
}

fn parse_frontmatter(content: &str) -> (Option<Frontmatter>, String) {
    let trimmed = content.trim_start();
    if !trimmed.starts_with("---") {
        return (None, content.to_string());
    }
    let after_open = &trimmed[3..];
    let after_open = after_open.strip_prefix('\r').unwrap_or(after_open);
    let after_open = after_open.strip_prefix('\n').unwrap_or(after_open);
    let Some(close_idx) = after_open.find("\n---") else {
        return (None, content.to_string());
    };
    let yaml_block = &after_open[..close_idx];
    (Some(parse_yaml_block(yaml_block)), String::new())
}

fn parse_yaml_block(block: &str) -> Frontmatter {
    let mut fm = Frontmatter {
        name: String::new(),
        description: String::new(),
        version: "1.0".to_string(),
        depends: Vec::new(),
        metadata: std::collections::HashMap::new(),
    };
    for line in block.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, raw_value)) = line.split_once(':') else {
            continue;
        };
        let key = key.trim();
        let raw_value = raw_value.trim();
        match key {
            "name" => fm.name = strip_quotes(raw_value).to_string(),
            "description" => fm.description = strip_quotes(raw_value).to_string(),
            "version" => fm.version = strip_quotes(raw_value).to_string(),
            "depends" => fm.depends = parse_string_array(raw_value),
            other => {
                fm.metadata
                    .insert(other.to_string(), strip_quotes(raw_value).to_string());
            }
        }
    }
    fm
}

fn strip_quotes(s: &str) -> &str {
    let s = s.trim();
    if s.len() >= 2 {
        let first = s.chars().next().unwrap();
        let last = s.chars().last().unwrap();
        if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
            return &s[1..s.len() - 1];
        }
    }
    s
}

fn parse_string_array(s: &str) -> Vec<String> {
    let s = s.trim();
    if !s.starts_with('[') || !s.ends_with(']') {
        return Vec::new();
    }
    let inner = &s[1..s.len() - 1];
    if inner.trim().is_empty() {
        return Vec::new();
    }
    inner
        .split(',')
        .map(|item| strip_quotes(item.trim()).to_string())
        .filter(|item| !item.is_empty())
        .collect()
}

fn collect_text_files(dir: &Path) -> Vec<(String, String)> {
    let mut files = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file()
                && let Some(name) = path.file_name().and_then(|n| n.to_str())
                && let Ok(content) = fs::read_to_string(&path)
            {
                files.push((name.to_string(), content));
            }
        }
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

fn extract_json_code_block(content: &str) -> Option<String> {
    let mut in_json = false;
    let mut result = String::new();
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("```json") {
            in_json = true;
            continue;
        }
        if trimmed == "```" && in_json {
            return Some(result.trim().to_string());
        }
        if in_json {
            result.push_str(line);
            result.push('\n');
        }
    }
    None
}
