#!/usr/bin/env bash
# Start/stop/status/migrate for Context-OS Client local data plane
# (Postgres + Redis + full Milvus). Writes desktop/runtime/client.env for
# client / API processes to source.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUNTIME_DIR="$ROOT/desktop/runtime"
COMPOSE_FILE="$RUNTIME_DIR/docker-compose.client.yml"
DATA_DIR="$RUNTIME_DIR/data"
ENV_FILE="$RUNTIME_DIR/client.env"
MIGRATIONS_DIR="$ROOT/avrag-rs/migrations"

# Defaults (localhost-only; offset from host system services)
CLIENT_PG_HOST="${CLIENT_PG_HOST:-127.0.0.1}"
CLIENT_PG_PORT="${CLIENT_PG_PORT:-5433}"
CLIENT_REDIS_HOST="${CLIENT_REDIS_HOST:-127.0.0.1}"
CLIENT_REDIS_PORT="${CLIENT_REDIS_PORT:-6380}"
CLIENT_MILVUS_HOST="${CLIENT_MILVUS_HOST:-127.0.0.1}"
CLIENT_MILVUS_PORT="${CLIENT_MILVUS_PORT:-19530}"
CLIENT_PG_USER="${CLIENT_PG_USER:-avrag}"
CLIENT_PG_PASSWORD="${CLIENT_PG_PASSWORD:-avrag}"
CLIENT_PG_DB="${CLIENT_PG_DB:-avrag_client}"

DATABASE_URL="${DATABASE_URL:-postgres://${CLIENT_PG_USER}:${CLIENT_PG_PASSWORD}@${CLIENT_PG_HOST}:${CLIENT_PG_PORT}/${CLIENT_PG_DB}}"
REDIS_URL="${REDIS_URL:-redis://${CLIENT_REDIS_HOST}:${CLIENT_REDIS_PORT}/0}"
MILVUS_URL="${MILVUS_URL:-http://${CLIENT_MILVUS_HOST}:${CLIENT_MILVUS_PORT}}"

die() { echo "desktop-local-stack: $*" >&2; exit 1; }
log() { echo "desktop-local-stack: $*"; }

command -v docker >/dev/null 2>&1 || die "docker not found"
docker compose version >/dev/null 2>&1 || die "docker compose plugin required"
[[ -f "$COMPOSE_FILE" ]] || die "missing compose file: $COMPOSE_FILE"

mkdir -p "$DATA_DIR"/{etcd,minio,milvus,pg,redis}

cd "$RUNTIME_DIR"
export COMPOSE_PROJECT_NAME=context-os-client

compose() {
  docker compose -f docker-compose.client.yml "$@"
}

port_open() {
  local port="$1"
  if (echo >/dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1; then
    return 0
  fi
  if command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "$port" 2>/dev/null; then
    return 0
  fi
  return 1
}

wait_ports() {
  local deadline=$((SECONDS + ${1:-90}))
  local port name
  for spec in "${CLIENT_PG_PORT}:postgres" "${CLIENT_REDIS_PORT}:redis" "${CLIENT_MILVUS_PORT}:milvus"; do
    port="${spec%%:*}"
    name="${spec##*:}"
    log "waiting for $name :$port …"
    while ! port_open "$port"; do
      if (( SECONDS >= deadline )); then
        die "timeout waiting for $name on :$port"
      fi
      sleep 1
    done
    log "$name :$port OK"
  done
}

write_env() {
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/desktop-local-stack.sh — do not commit secrets for shared envs.
# Source:  set -a && source desktop/runtime/client.env && set +a
# Or:      export \$(grep -v '^#' desktop/runtime/client.env | xargs)

CLIENT_PG_HOST=${CLIENT_PG_HOST}
CLIENT_PG_PORT=${CLIENT_PG_PORT}
CLIENT_REDIS_HOST=${CLIENT_REDIS_HOST}
CLIENT_REDIS_PORT=${CLIENT_REDIS_PORT}
CLIENT_MILVUS_HOST=${CLIENT_MILVUS_HOST}
CLIENT_MILVUS_PORT=${CLIENT_MILVUS_PORT}

DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}
MILVUS_URL=${MILVUS_URL}

# Optional process flags for avrag-api / worker against this stack
AVRAG_RUN_MIGRATIONS=true
AVRAG_MIGRATIONS_DIR=${MIGRATIONS_DIR}
EOF
  log "wrote $ENV_FILE"
}

print_env_hint() {
  echo
  echo "Client process env:"
  echo "  DATABASE_URL=$DATABASE_URL"
  echo "  REDIS_URL=$REDIS_URL"
  echo "  MILVUS_URL=$MILVUS_URL"
  echo "  file: $ENV_FILE"
}

run_migrate() {
  [[ -d "$MIGRATIONS_DIR" ]] || die "migrations dir missing: $MIGRATIONS_DIR"
  write_env

  if ! port_open "$CLIENT_PG_PORT"; then
    die "Postgres not reachable on :${CLIENT_PG_PORT} — run: $0 up"
  fi

  # Prefer sqlx-cli (tracks _sqlx_migrations + checksums).
  if command -v sqlx >/dev/null 2>&1; then
    log "running sqlx migrate run …"
    sqlx migrate run \
      --source "$MIGRATIONS_DIR" \
      --database-url "$DATABASE_URL"
    log "migrations applied"
    return 0
  fi

  # Fallback: cargo-installed sqlx often lives under ~/.cargo/bin
  if [[ -x "${HOME}/.cargo/bin/sqlx" ]]; then
    log "running ~/.cargo/bin/sqlx migrate run …"
    "${HOME}/.cargo/bin/sqlx" migrate run \
      --source "$MIGRATIONS_DIR" \
      --database-url "$DATABASE_URL"
    log "migrations applied"
    return 0
  fi

  die "sqlx CLI not found. Install: cargo install sqlx-cli --no-default-features --features postgres
Then: $0 migrate"
}

cmd="${1:-status}"

case "$cmd" in
  up)
    log "starting Postgres + Redis + Milvus stack…"
    compose up -d
    wait_ports 120
    write_env
    print_env_hint
    log "stack up. Optional: $0 migrate"
    ;;
  ensure)
    # Idempotent: up + wait + env + migrate
    log "ensure: bring stack up and migrate schema…"
    compose up -d
    wait_ports 120
    write_env
    run_migrate
    print_env_hint
    log "ensure complete"
    ;;
  down)
    compose down
    log "stopped (volumes under $DATA_DIR retained)"
    ;;
  status)
    compose ps || true
    echo
    for spec in "${CLIENT_PG_PORT}:postgres" "${CLIENT_REDIS_PORT}:redis" "${CLIENT_MILVUS_PORT}:milvus"; do
      port="${spec%%:*}"
      name="${spec##*:}"
      if port_open "$port"; then
        echo "  $name :$port  OK"
      else
        echo "  $name :$port  DOWN"
      fi
    done
    if [[ -f "$ENV_FILE" ]]; then
      echo
      echo "  client.env: $ENV_FILE (present)"
    else
      echo
      echo "  client.env: missing (run: $0 write-env | up | ensure)"
    fi
    print_env_hint
    ;;
  write-env|env)
    write_env
    print_env_hint
    ;;
  migrate)
    run_migrate
    ;;
  logs)
    compose logs -f --tail=100
    ;;
  *)
    die "usage: $0 {up|ensure|down|status|write-env|migrate|logs}"
    ;;
esac
